version: "3.3"

services:
  gitlab:
    container_name: gitlab
    hostname: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${PUBLIC_HOSTNAME}'
        # registry_external_url 'https://${PUBLIC_HOSTNAME}:5000'

    volumes:
      - "/home/ec2-user/gitlab-config/certs/${PUBLIC_HOSTNAME}.crt:/etc/gitlab/ssl/${PUBLIC_HOSTNAME}.crt"
      - "/home/ec2-user/gitlab-config/certs/${PUBLIC_HOSTNAME}.key:/etc/gitlab/ssl/${PUBLIC_HOSTNAME}.key"
#      - "/srv/gitlab/config:/etc/gitlab"
#      - "/srv/gitlab/logs:/var/log/gitlab"
#      - "/srv/gitlab/data:/var/opt/gitlab"
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:2222:22

  gitlab-runner:
    container_name: gitlab-runner
    hostname: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - "/srv/gitlab-runner/config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
